export const products = 
[
    {
       idProduct:1,
       prodName:"CBR 300",
       cylinder:289,
       brand:"Honda",
       year: 2019,
       miles : 2300,
       shortDesc:"Honda CBR 300 Mod 2019, 2300kms!",
       description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam minima unde enim exercitationem quidem aliquid culpa qui explicabo, non eius adipisci, consequatur",
       url:"/item/1",
       category:"supersport",
       image:require("../images/cbr300.jpg"),
       alt:"Honda CBR 300",
       price:5300,
       stock:5,
       initial:1
    },
    {
       idProduct:2,
       prodName:"Ninja 400",
       cylinder:399,
       brand:"Kawasaki",
       year: 2022,
       miles : 0,
       shortDesc:"Kawasaki Ninja 400 0Km!",
       description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam minima unde enim exercitationem quidem aliquid culpa qui explicabo, non eius adipisci, consequatur",
       url:"/item/2",
       category:"supersport",
       image:require("../images/ninja400.jpg"),
       alt:"Kawasaki Ninja 400",
       price:13500,
       stock:5,
       initial:1
    },
       {
       idProduct:3,
       prodName:"600i",
       cylinder:600,
       brand:"Benelli",
       year: 2022,
       miles : 0,
       shortDesc:"Benelli 600i 0kms!",
       description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam minima unde enim exercitationem quidem aliquid culpa qui explicabo, non eius adipisci, consequatur",
       url:"/item/3",
       category:"naked",
       image:require("../images/benelli600.jpg"),
       alt:"Benelli 600i",
       price:12500,
       stock:5,
       initial:1
    },
    {
       idProduct:4,
       prodName:"Vitpilen  401",
       cylinder:400,
       brand:"Husqvarna",
       year: 2021,
       miles : 0,
       shortDesc:"Husqvarna Vitpilen  401 - 0kms!",
       description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam minima unde enim exercitationem quidem aliquid culpa qui explicabo, non eius adipisci, consequatur",
       url:"/item/4",
       category:"scrambler",
       image:require("../images/husqvarna401.jpg"),
       alt:"Husqvarna Vitpilen  401",
       price:10500,
       stock:5,
       initial:1
    },
       {
       idProduct:5,
       prodName:"Leoncino 500",
       cylinder:500,
       brand:"Benelli",
       year: 2022,
       miles : 0,
       shortDesc:"Benelli Leoncino 500 - 0kms!",
       description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam minima unde enim exercitationem quidem aliquid culpa qui explicabo, non eius adipisci, consequatur",
       url:"/item/5",
       category:"scrambler",
       image:require("../images/leoncino500.jpg"),
       alt:"Benelli Leoncino 500",
       price:10200,
       stock:5,
       initial:1
    },
    {
       idProduct:6,
       prodName:"Tornado XR 250",
       cylinder:289,
       brand:"Kawasaki",
       year: 2020,
       miles : 2300,
       shortDesc:"Honda Tornado XR 250 2020, 2300kms!",
       description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam minima unde enim exercitationem quidem aliquid culpa qui explicabo, non eius adipisci, consequatur",
       url:"/item/6",
       category:"cross",
       image:require("../images/tornado250.jpg"),
       alt:"Honda Tornado XR 250",
       price:4000,
       stock:5,
       initial:1
    },
       {
       idProduct:7,
       prodName:"TRK 502X",
       cylinder:500,
       brand:"Benelli",
       year: 2022,
       miles : 0,
       shortDesc:"Benelli TRK 502X - 0kms!",
       description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam minima unde enim exercitationem quidem aliquid culpa qui explicabo, non eius adipisci, consequatur",
       url:"/item/7",
       category:"touring",
       image:require("../images/trk502.jpg"),
       alt:"Benelli TRK 502X",
       price:12000,
       stock:5,
       initial:1
    },
    {
       idProduct:8,
       prodName:"Ninja H2 1000",
       cylinder:998,
       brand:"Kawasaki",
       year: 2018,
       miles : 6000,
       shortDesc:"Kawasaki Ninja H2 1000 - 2018, 6000 kms!",
       description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam minima unde enim exercitationem quidem aliquid culpa qui explicabo, non eius adipisci, consequatur",
       url:"/item/8",
       category:"supersport",
       image:require("../images/ninjaH2.jpg"),
       alt:"Kawasaki Ninja H2 100",
       price:68000,
       stock:5,
       initial:1
    }
 ]